### ISSUE TITLE
add support for custom meta data

### ISSUE THREAD

**Issue by foxpcteam** [jesperbjerke/wa-fronted#11]
Hi,
i am using some plugins that use custom post types with custom meta.
how can i add support for custom meta so the editor can edit meta data in the front?

Thanks

**Comment by jesperbjerke** [comment]
This is part of a planned feature "Native custom fields support". So as of now, your best bet is to build an extension to wa-fronted to support these meta fields/plugins. Look in the "extensions" folder and the woocommerce extension. Otherwise sit tight and this feature will be implemented when I've got time.

**Comment by jesperbjerke** [comment]
Added in v0.6.5-alpha

**Comment by foxpcteam** [comment]
Great Thanks!
